# Generated by Django 6.0.7 on 2026-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطبيب')),
                ('specialty', models.CharField(max_length=100, verbose_name='التخصص')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
