# Generated by Django 6.1 on 2026-08-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='متاح للحجز'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='store.service', verbose_name='الخدمات'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.CharField(max_length=100, verbose_name='الطبيب'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.CharField(max_length=100, verbose_name='المريض'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=100, verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(verbose_name='الوقت'),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='رقم العيادة')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='store.doctor', verbose_name='الطبيب')),
            ],
        ),
    ]
